import { c, C } from "./complex.js";
import { m, M2 } from "./cmat.js";
import { Network } from "./rf.js";

/**
 * Touchstone v1 风格读写器（两端口）。
 * 支持：
 *  - 选项行 `# <unit> <param> <format> R <z0>`（缺失时按 kHz/S/RI/R50）；
 *  - 格式 RI（实部 虚部）、MA（幅度 角度°）、DB（dB 角度°）；
 *  - 注释行 `!`；
 *  - 两端口频率记录固定 4 行 * 3 对 = 12 个噪声系数列顺序为
 *    S11 S21 S12 S22，每行 (前向在左、后向在右，Touchstone 标准排布)。
 */
export interface TouchstoneParseResult {
  network: Network;
  warnings: string[];
  freqUnit: string;
  format: "RI" | "MA" | "DB";
}

const UNIT_TO_HZ: Record<string, number> = {
  hz: 1,
  khz: 1e3,
  mhz: 1e6,
  ghz: 1e9,
};

export function parseTouchstone(text: string, name?: string): TouchstoneParseResult {
  const warnings: string[] = [];
  let freqUnit = "ghz";
  let format: "RI" | "MA" | "DB" = "MA";
  let z0 = 50;
  let paramType = "S";

  const tokens: number[] = [];
  const rows: number[][] = [];
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line) continue;
    if (line.startsWith("!")) continue;
    if (line.startsWith("#")) {
      const toks = line.slice(1).trim().split(/\s+/);
      for (let i = 0; i < toks.length; i++) {
        const tk = toks[i]!.toLowerCase();
        if (UNIT_TO_HZ[tk] !== undefined) freqUnit = tk;
        else if (tk === "s" || tk === "y" || tk === "z" || tk === "h" || tk === "g") paramType = tk.toUpperCase();
        else if (tk === "ri" || tk === "ma" || tk === "db") format = tk.toUpperCase() as "RI" | "MA" | "DB";
        else if (tk === "r" && toks[i + 1] !== undefined) z0 = parseFloat(toks[i + 1]!);
      }
      continue;
    }
    const nums = line.split(/[\s,]+/).filter(Boolean).map(Number);
    if (nums.some((x) => !Number.isFinite(x))) {
      throw new Error(`Touchstone 行含非数值: ${rawLine}`);
    }
    rows.push(nums);
    tokens.push(...nums);
  }
  if (paramType !== "S") {
    warnings.push(`文件声明参数类型 ${paramType}，本台仅按 S 参数处理`);
  }

  // 每个频点：freq + 4*2 = 9 个数；允许跨行（Touchstone 允许自由换行）。
  const stride = 9;
  if (tokens.length === 0 || tokens.length % stride !== 0) {
    throw new Error(
      `两端口 Touchstone 记录长度非法：共 ${tokens.length} 个数，应为 9 的倍数`,
    );
  }

  const mult = UNIT_TO_HZ[freqUnit] ?? 1e9;
  const freq: number[] = [];
  const sParam: M2[] = [];
  for (let base = 0; base < tokens.length; base += stride) {
    const f = tokens[base]! * mult;
    if (freq.length && f <= freq[freq.length - 1]!) {
      throw new Error(`频率必须严格递增，违例 @ ${f} Hz`);
    }
    const p = (offset: number): C => {
      const a = tokens[base + 1 + offset * 2]!;
      const b = tokens[base + 2 + offset * 2]!;
      if (format === "RI") return c(a, b);
      const angRad = (b * Math.PI) / 180;
      if (format === "MA") return c(a * Math.cos(angRad), a * Math.sin(angRad));
      const mag = Math.pow(10, a / 20);
      return c(mag * Math.cos(angRad), mag * Math.sin(angRad));
    };
    // 标准顺序: S11(0) S21(1) S12(2) S22(3)
    const s11 = p(0);
    const s21 = p(1);
    const s12 = p(2);
    const s22 = p(3);
    freq.push(f);
    sParam.push(m(s11, s12, s21, s22));
  }
  return {
    network: { freq, sParam, z0: [z0, z0], name },
    warnings,
    freqUnit,
    format,
  };
}

/** 输出 RI 格式、GHz、两端口 Touchstone。 */
export function writeTouchstone(n: Network): string {
  if (n.z0[0] !== n.z0[1]) {
    throw new Error("Touchstone v1 不支持逐端口不同参考阻抗；请先统一重归一化");
  }
  const lines: string[] = [
    `! Generated by 参数面去嵌台 (reference-plane de-embed bench)`,
    `# GHz S RI R ${n.z0[0]}`,
  ];
  n.freq.forEach((f, i) => {
    const s = n.sParam[i]!;
    const ghz = f / 1e9;
    const pair = (x: C) => `${x.re.toPrecision(10)} ${x.im.toPrecision(10)}`;
    lines.push(`${ghz.toPrecision(10)} ${pair(s.m00)} ${pair(s.m10)} ${pair(s.m01)} ${pair(s.m11)}`);
  });
  return lines.join("\n") + "\n";
}
